<h1><?php echo $this->book->getTitle(); ?>, <small>by <a href="<?php echo $this->url('application/default', array('controller'=>'profile', 'action' => 'show','id'=>$this->book->getCreator()->getUsername())); ?>"><?php echo $this->book->getCreator()->getUsername(); ?></a></small></h1>

<div class="bs-callout bs-callout-info">
    <?php echo $this->book->getDescription(); ?>
</div>
<?php foreach($this->book->getPages() as $page): ?>
    <div class="jumbotron"><?php echo $page->getText(); ?></div>
<?php endforeach; ?>
