<div class="container">
    <h2>Our community</h2>
    <div class="row">
        <div class="col-sm-12">
            <?php foreach($users as $user): ?>
            <div class="row">
                <div class="col-sm-2">
                    <img src="https://s.gravatar.com/avatar/<?php echo md5($user->getEmail()); ?>?s=250&d=mm" class="img-circle" style="width: 100%;" alt="user avatar">
                </div>
                <div class="col-sm-10">
                    <h3><?php echo $user->getUsername(); ?></h3>
                    <a href="<?php echo $this->url('application/default',array('controller'=>'profile','action'=>'show','id'=>$user->getUsername())); ?>" class="btn btn-default btn-sm">
                        Find out more...
                    </a>
                </div>
            </div>
            <hr/>
            <?php endforeach; ?>
        </div>
    </div>
</div>