<div class="container">
    <div class="row">
        <div class="col-sm-2">
            <h2>Projects</h2>
            <p class="alert alert-danger">Sorry, this feature is not yet available.</p>
        </div>
        <div class="col-sm-8">
            <h2>Stories / Activity</h2>
            <p>
                Donec id elit non mi porta gravida at eget metus.
                Fusce dapibus, tellus ac cursus commodo, tortor
                mauris condimentum nibh, ut fermentum massa justo
                sit amet risus. Etiam porta sem malesuada magna
                mollis euismod. Donec sed odio dui.
            </p>
            <h2>Stories / Activity</h2>
            <p>
                Donec id elit non mi porta gravida at eget metus.
                Fusce dapibus, tellus ac cursus commodo, tortor
                mauris condimentum nibh, ut fermentum massa justo
                sit amet risus. Etiam porta sem malesuada magna
                mollis euismod. Donec sed odio dui.
            </p>
            <h2>Stories / Activity</h2>
            <p>
                Donec id elit non mi porta gravida at eget metus.
                Fusce dapibus, tellus ac cursus commodo, tortor
                mauris condimentum nibh, ut fermentum massa justo
                sit amet risus. Etiam porta sem malesuada magna
                mollis euismod. Donec sed odio dui.
            </p>
        </div>
        <div class="col-sm-2">
            <h2>Favourited Stories</h2>
            <p class="alert alert-danger">Sorry, this feature is not yet available.</p>
        </div>
    </div>
</div>