<div class="container">
    <h2>My name is <?php echo $this->user->getUsername(); ?></h2>
    <div class="row">
        <div class="col-sm-12">
            <?php if(count($this->user->getBooks())): ?>
                <h3>I wrote the following books:</h3>
                <?php foreach ($this->user->getBooks() as $book): ?>
                    <h4><?php echo $book->getTitle(); ?></h4>
                    <p>
                        <?php echo $book->getDescription(); ?>
                    </p>
                    <a href="<?php echo $this->url('application/default',array('controller'=>'book','action'=>'read','id'=>$book->getId())); ?>" class="btn btn-default btn-sm"><?php echo $this->translate('Read more...'); ?></a>
                <?php endforeach; ?>
            <?php else: ?>
                <h3>I haven't written any book yet.</h3>
            <?php endif; ?>
        </div>
    </div>
</div>