<div class="container">
    <div class="col-sm-6">
        <?php echo $this->zfcUserLogin; ?>
    </div>
    <div class="col-sm-6">
        <?php
            $socialSignIn = true;
            foreach ($this->options->getEnabledProviders() as $provider) {
                if ($socialSignIn) {
                    echo '<h1>Social Registration</h1>';
                    $socialSignIn = false;
                }
                echo '<dd>' . $this->socialSignInButton($provider, $this->redirect) . '</dd>';
            }
        ?>
    </div>
</div>