<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Read, Write, Explore')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo-small.png'))
                ->prependStylesheet($this->basePath() . '/styles/styles.css')
                ->prependStylesheet($this->basePath() . '/styles/bootstrap-theme.css')
                ->prependStylesheet($this->basePath() . '/styles/bootstrap.css')
        ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div class="nav-bar">
            <div class="nav-wrap">
                <div class="navbar" role="navigation">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <div class="bar">

                            </div>
                            <div class="nav-logo" >
                                <a href="<?php echo $this->url('home'); ?>"><img src="<?php echo $this->basePath(); ?>/img/logo-small.png" alt="logo" class="center-block"/></a>
                            </div>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li>
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'index')); ?>">Home</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'book')); ?>">Library</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'profile')); ?>">Community</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'book', 'action' => 'create')); ?>">Creator</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="landing" data-stellar-background-ratio="0.2">
            <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="logo" class="center-block"/>
        </div>
        <div class="log-in">
            <div class="container">
                <a>Register</a> | <a>Log In</a>
            </div>
        </div>

        <?php echo $this->content; ?>

        <div class="footer" data-stellar-background-ratio="0.2">
            <div class="container">
                <hr />
                <div class="row">
                <p class="col-sm-4">
                    2014 - Team Read, Write, Explore
                </p>
                <p class="col-sm-offset-5 col-sm-3 text-right">
                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action'=> 'about')); ?>" style="color:#FFFFFF;">Meet the team</a>
                </p>
                </div>
            </div>
        </div>

        <?php
        echo $this->inlineScript()
                ->prependFile($this->basePath() . '/scripts/rwe.js')
                ->prependFile($this->basePath() . '/scripts/bootstrap.js')
                ->prependFile($this->basePath() . '/scripts/jquery.stellar.min.js')
                ->prependFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js')
                ->prependFile('http://code.jquery.com/jquery-1.11.0.min.js')
        ?>
    </body>
</html>
