<div class="slide" >
    <div class="team-wrap">
        <h1>Meet the Team</h1>
        <div class="row" >
            <div class="col-sm-4" >
                <div class="avatar-wrap">
                    <img id="brian" class="avatar img-circle center-block" src="https://secure.gravatar.com/avatar/ff61892c49c5820d90d7d68e95b6fd8d?s=250&d=mm" alt="Brian" />
                    <h3>Brian Douglas</h3>
                    <p>
                        Frontend Design and Development
                    </p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="avatar-wrap">
                    <img class="avatar  img-circle center-block" src="http://secure.gravatar.com/avatar/84a7d4972cb4939279a6cbd8f5060743?s=250&d=mm" alt="Finlay" />
                    <h3>Finlay Niven</h3>
                    <p>
                        UX Specialist
                    </p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="avatar-wrap">
                    <img class="avatar img-circle center-block" src="https://secure.gravatar.com/avatar/e5d996ead1e3f9bd03f4af376e86aedd?s=250&d=mm" alt="Paul" />
                    <h3>Paul Lapok</h3>
                    <p>
                        Database Engineer
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="avatar-wrap">
                <img class="avatar img-circle center-block" src="https://secure.gravatar.com/avatar/24d35580229a8b5f07968682af00a551?s=250&d=mm" alt="Thomas" />
                <h3>Thomas Dutrion</h3>
                <p>
                    Backend Development
                </p>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="avatar-wrap">
                <img class="avatar img-circle center-block" src="https://secure.gravatar.com/avatar/517839cfbdb7a0e220c154c1810fed91?s=250&d=mm" alt="Lee" />
                <h3>Lee Robertson</h3>
                <p>
                    Sigma.js and UX
                </p>
            </div>
        </div>
    </div>
</div>