<div class="slide" >
    <div class="container row">
        <div class="slidewrap">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <h1>'Read, Write, Explore'</h1>
                <p>Welcome to a brand new site for the creation and sharing of
                    adventure books. Just like the adventure books of your childhood, here
                    you will be able to go on grand quests and choose the paths you want to
                    take. However at Read, Write, Explore we don't just want you to go on
                    adventures we also want you to write your own adventures. Using our
                    simple creator you can let your imagination run wild and create a brand
                    new adventure. You can then share your new book with the fantastic
                    community on the site as well as create your very own eBook to read and
                    share. <br />
                <h4></h4>Enjoy!</h4>
                </p>
            </div>
            <div class="col-sm-1"></div>
        </div>
    </div>
</div>

<div class="slide-small" data-stellar-background-ratio="0.6"></div>

<div class="slide-alt" data-stellar-background-ratio="0.5">
    <div class="slidewrap-alt"></div>
</div>

<div class="slide-small-alt" data-stellar-background-ratio="0.6">

</div>

<div class="slide" >
    <h2>Meet the Team</h2>
    <div class="row" >
        <div class="col-sm-4" >
            <img id="brian" class="avatar img-circle center-block" src="https://secure.gravatar.com/avatar/ff61892c49c5820d90d7d68e95b6fd8d?s=250&d=mm" alt="Brian" />
        </div>
        <div class="col-sm-4">
            <img class="avatar  img-circle center-block" src="http://secure.gravatar.com/avatar/84a7d4972cb4939279a6cbd8f5060743?s=250&d=mm" alt="Finlay" />
        </div>
        <div class="col-sm-4">
            <img class="avatar img-circle center-block" src="https://secure.gravatar.com/avatar/e5d996ead1e3f9bd03f4af376e86aedd?s=250&d=mm" alt="Paul" />
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <img class="avatar img-circle center-block" src="https://secure.gravatar.com/avatar/24d35580229a8b5f07968682af00a551?s=250&d=mm" alt="Thomas" />
        </div>
        <div class="col-sm-6">
            <img class="avatar img-circle center-block" src="https://secure.gravatar.com/avatar/517839cfbdb7a0e220c154c1810fed91?s=250&d=mm" alt="Lee" />
        </div>
    </div>
</div>