<div class="slide" >
    <div class="container">
        <div class="slidewrap">
            <h1>'Read, Write, Explore'</h1>
            <p>
                Welcome to a brand new site for the creation and sharing of
                adventure books. Just like the adventure books of your childhood, here
                you will be able to go on grand quests and choose the paths you want to
                take. However at Read, Write, Explore we don't just want you to go on
                adventures we also want you to write your own adventures. Using our
                simple creator you can let your imagination run wild and create a brand
                new adventure. You can then share your new book with the fantastic
                community on the site as well as create your very own eBook to read and
                share.
                <br />
            <h4>Enjoy!</h4>
            </p>
        </div>
    </div>
</div>

<div class="slide-small" data-stellar-background-ratio="0.6"></div>

<div class="slide-alt" data-stellar-background-ratio="0.5">
    <div class="container">

        <div class="slidewrap-alt">
            <h1> Inspiration </h1>
            <p>
                Do you remember gamebooks? You know, the ones with the choice at the end
                of a page, where you were in control of the adventure. Here at Read, Write,
                Explore we grew up reading adventures from great series like Choose Your Own
                Adventure and Give Yourself Goosebumps. The freedom to explore and use your
                imagination is exactly what we wanted to capture when we set out to create
                the site. We hope that by giving you the freedom to create your very own
                stories the spirit of these books from everybody's childhood will live on.
            </p>
            <h4> Get Exploring!</h4>

        </div>
    </div>
</div>

<div class="slide-small-alt" data-stellar-background-ratio="0.6">

</div>